### ISSUE TITLE
Question: The task includes an option with an undefined variable. 

### ISSUE THREAD

**Issue by DeanKamali** [pgkehle/ansible-mongodb#4]
Here is my config 

```
- hosts: servers
  become: false
  vars:
    rs_port:                "27017"
    mongodb_type:           "daemon"
    replica_set_name:       "rs0"
    cluster_role:           "shardsvr"
    rs_server_group_id:     "rs_mongo"
    app_users:
      - { db_name: "", user: "", pwd: "", roles: ["readWrite", "userAdmin"] } 
  roles:
    - { role: pgkehle.mongodb, flags: ['init'] }        
    - { role: pgkehle.mongodb, flags: ['config_save'] }        
    - { role: pgkehle.mongodb, flags: ['storage_init'] }        
    - { role: pgkehle.mongodb, flags: ['rs_init'] }
```
I'm getting the following error

https://asciinema.org/a/CksDLsDWChibot2Ay7P1WQRpI 

I'm wondering if I need to structure my inventory file in specific way, to include missing variables as attributes?

**Comment by isaackehle** [comment]
Yes, you do have to configure your inventory file properly.   This playbook is intended to use a group of servers from your inventory, and allow you to designate which group you would like to use, via the `rs_server_group_id` variable. 

There will be more info on how to do that on the ansible site of course, but as a quick and dirty example: 

## Inventory Directory Structure
```
inventories
├── app-servers
├── group_vars
|   ...
│   ├── app-cfg-servers.yml
│   ├── app-shard-servers.yml
│   ├── app-shd00-servers.yml
│   ├── app-shd01-servers.yml
│   ...
```

## Set variables for one specific group example
```
> cat inventories/group_vars/app-shd00-servers.yml
---

# MongoDB Cluster Definitions - Group Settings
replica_set_name:     "app-shd00"
replica_set_group_id: "app-shd00-servers"
```

## Defining the host names in the groups
```
> cat inventories/app-servers

...
[app-cfg-servers]
app-cfg-rs0
app-cfg-rs1
app-cfg-rs2

[app-shd00-servers]
app-shd00-rs0
app-shd00-rs1
app-shd00-rs2

[app-shd01-servers]
app-shd01-rs0
app-shd01-rs1
app-shd01-rs2

[app-shard-servers:children]
app-shd00-servers
app-shd01-servers

...

```

Thus for that example of the shard server 0 replica set: 

```
- hosts: servers
  become: false
  vars:
    rs_port:                "27017"
    mongodb_type:           "daemon"

-- Do not set this here.  It is set in prep-vars.yml
--    rs_server_group_id:     "rs_mongo"

-- These are set in 'app-shd00-servers.yml'
--  replica_set_name:       "rs0"
--  cluster_role:           "shardsvr"
--	replica_set_name:     	"app-shd00"
--	replica_set_group_id: 	"app-shd00-servers"

    app_users:
      - { db_name: "", user: "", pwd: "", roles: ["readWrite", "userAdmin"] } 
  roles:
    - { role: pgkehle.mongodb, flags: ['init'] }        
    - { role: pgkehle.mongodb, flags: ['config_save'] }        
    - { role: pgkehle.mongodb, flags: ['storage_init'] }        
    - { role: pgkehle.mongodb, flags: ['rs_init'] }
```

...which is used in `prep-vars.yml`:

```
  - name: Set the rs group name from cfg_server_name
    set_fact:
      rs_server_group_id: "{{ cfg_server_group_id }}"    
    when:
      - cfg_server_group_id is defined

  - name: Set the rs group name from replica_set_name
    set_fact:
      rs_server_group_id: "{{ replica_set_group_id }}"
    when:
      - replica_set_group_id is defined

```

**Comment by isaackehle** [comment]
As a follow up, it seems my documentation is a bit misleading.  I'll update the docs on the next go-around.

**Comment by isaackehle** [comment]
It's been 11 months or so since this was opened.  I'm not sure if this is still an outstanding issue.  Please confirm.

**Comment by PhanSon95** [comment]
Hi @pgkehle . Could you provide path where will place this configuration inside ansible project, thank you
```
cfg_server:
  name: "my-cfg" # (Required)
  group: "my-cfg-servers" # (Required) Always pass in the group id used for the config servers

replica_set:
  name: "my-cfg" # name of the replica set for the config server (prefix of fqdn)
  group: "my-cfg-servers" # group name for all servers in the replica set
```

Replica Set Only
```
cluster_role: "replicaSet"
```
Router Server
```
cluster_role: "router"
```
Config Server
```
cluster_role: "config"
replica_set:
  name: "my-cfg" # name of the replica set for the config server (prefix of fqdn)
  group: "my-cfg-servers" # group name for all servers in the replica set
```
Shard Server
```
cluster_role: "shard"
replica_set:
  name: "db-data" # name of the replica set for the shard server (prefix of fqdn)
  group: "db-data-servers" # group name for all servers in the replica set
```
